### ISSUE TITLE
Get various hostnames with smf-upf-pfcp values config

### ISSUE THREAD

**Issue by rodrigosanzsanz** [Gradiant/5g-charts#143]
Hello!

I had success in launch an additional UPF usign OpenVerso charts, and changing config values from outside. This is a great job and allow me to use different configuration from base chart.

But actually , I have the following problem, when I update with 'helm upgrade...' as follows:

helm upgrade open5gs open5gs --values new-config-2dnn.yaml

The part of SMF config gets only the last Hostname define (in the case below 'internet2'

...
smf:
  config:
    pcrf:
      enabled: false

    subnetList:
      - addr: 10.45.0.1/16
        dnn: internet
      - addr: 10.46.0.1/16
        dnn: internet2
    upf:      
      pfcp:
        hostname: "open5gs-upf-pfcp"
        dnn: internet
        hostname: "open5gs-upf2-pfcp"
        dnn: internet2
...    

Maybe it is needed to change something in the values config map to allow to get both hostnames?? I hope you can check if there is any issue to get both upf-pfcp--> 2xhostnames

Thanks in advance!

**Comment by rodrigosanzsanz** [comment]
[5gconfig-upd-2upf-2dnn.txt](https://github.com/Gradiant/openverso-charts/files/13633993/5gconfig-upd-2upf-2dnn.txt)

Please, find attached the complete config file, with txt extension.

![image](https://github.com/Gradiant/openverso-charts/assets/133344742/61caf565-e7ca-4c32-ae96-15a8c3fe9d21)

Any help is welcome :)

Take into account that if the order of upf-pfcp is interchanged, the upf selection considered is only the last one.

Regards

**Comment by rodrigosanzsanz** [comment]
Thanks Carlos!, Yes, this was the issue, I will make some test, but issue is clear.
I will make some make around at the moment but if I have some time to prepara a PR I will let you know. Thanks!

**Comment by avrodriguezgrad** [comment]
Hi Rodrigo,

Sorry for the delay. You can see the configmap of the SMF using `kubectl get cm <configmap-name> -o yaml` and, there, you can check if the subnetList is working.

I cannot check yet if its working or not, but the behavior is the same as the slice list, and that's working.

If you solved it, feel free to PR if it's needed. 

Thanks again for using both charts and images projects!
