### ISSUE TITLE
[Bug]: UPF-GTPU Interface exposed as LoadBalancer not working

### ISSUE THREAD

**Issue by anabel1012** [Gradiant/5g-charts#167]
### Steps to reproduce

Hello,

I'm testing the new version of your Open5Gs charts (2.2.0) with a values configuration similar to the one I had in the previous version (2.1.0). In this deployment I'm exposing the AMF-NGAP and UPF-GTPU interfaces as LoadBalancer services. To my surprise, the line 83-84 "advertise" (in the config-upf-gtpu section) of the values.yaml of open5gs-upf chart has disappeared. Despite modifying the code and putting it by myself, it doesn't seem to take the value. Why has it been deleted?  Do I have to configure it differently now?

Thanks in advance

### Expected behaviour

The expected behaviour is to have Internet connectivity in the UE and seeing that the IP Address that the UPF is exposing is the one given to the LoadBalancer, not the pod one.

### Observed Behaviour

<img width="1345" alt="image" src="https://github.com/Gradiant/5g-charts/assets/26376831/f2de81d8-3002-436c-a9bd-82c26b1dce88">

The IP Address that I see in the PDUSessionResourceSetupRequest package is the one from the pod, not the LoadBalancer one.

**Comment by avrodriguezgrad** [comment]
Hi @anabel1012 

Can you try the following branch? https://github.com/Gradiant/5g-charts/tree/add-advertise

With the change of the config files of open5gs, we forgot to add that field. Tell me if it works, and I'll merge the branch.

BR,
Álvaro

**Comment by anabel1012** [comment]
Hi @avrodriguezgrad 

It works now, so you can merge the branch. Thank you for the quick response.

BR,
Anabel
