### ISSUE TITLE
[Bug]: Bug Report and Feature Request: Variable for NRF PLMN ID Configuration

### ISSUE THREAD

**Issue by anabel1012** [Gradiant/5g-charts#169]
### Steps to reproduce

Hello!

I'm testing the new version of your Open5Gs charts (2.2.0) with a values configuration similar to the one I had in the previous version (2.1.0). One of the new features of the new version is the addition of 5G roaming. For this reason, it is also necessary to indicate the PLMN ID in the NRF function (nrf.yaml): 

```
nrf:
  serving: # 5G roaming requires PLMN in NRF
  - plmn_id:
      mcc: 999
      mnc: 70
```

If you use the default values (values.yaml) of your helm everything works normally because the default PLMN ID 999 70 is used, which is the same as the one defined in the nrf.yaml file. However, if you change the plmn id through the AMF variables, the configuration becomes inconsistent. Would it be possible that the values used in NRF.yaml for mcc and mnc could be passed as a variable in NRF function and not have to modify the function code itself?

Thanks in advance,
Anabel

### Expected behaviour

NRF PLMN ID values passed as variable

### Observed Behaviour

NRF PLMN ID values defined in the code

**Comment by avrodriguezgrad** [comment]
Hi @anabel1012 

Yes, you are right. Currently, as we are not researching about roaming, we have not templated this part of the NRF config. I invite you to make the necessary changes, test it and create a PR to solve this.

BR,
Álvaro

**Comment by anabel1012** [comment]
Hi @avrodriguezgrad ,

Perhaps I was not clear enough. I am not testing 5G Roaming, but with the addition of this functionality it is now necessary to indicate the PLMN ID also in the NRF function, regardless of you are using roaming or not. So, if you want to use another PLMN ID and you only pass it as a parameter in the AMF function your core will be misconfigured. I can work on it and do the PR.

Br,
Anabel

**Comment by avrodriguezgrad** [comment]
Hi @anabel1012 

Yes, I did not know that it is necessary for the good behaviour, so I have changed the chart.

BR,
Álvaro
