### ISSUE TITLE
Manual Scalability in Open5Gs Chart

### ISSUE THREAD

**Issue by kirankumar-Athirala** [Gradiant/5g-charts#179]
I am planning to utilize the Gradiant/5g-charts/charts/open5gs chart for deploying the Open5G core in my standalone Kubernetes environment. I seek clarification on the chart's capability to auto-configure manually scaled AMF and SMF functionalities.

Specifically, if I manually scale the AMF functionality, will the newly launched AMF pod be able to connect seamlessly to the Open5G core and operate with the existing configuration without any manual intervention? Additionally, will both the original and new AMF instances function correctly with the shared configuration?

If this is possible, could you please explain the process to achieve this so that I can implement it accordingly? If it is not feasible, I would appreciate any guidance or modifications required to achieve this functionality.

Thank you for your assistance.

Best regards,
kirankumar athirala

**Comment by avrodriguezgrad** [comment]
Hi @kirankumar-Athirala 

We have not yet investigated how Open5GS behaves in terms of cloud-native scalability. This is an area we have on our roadmap, but unfortunately I can't help you with this at this stage.

BR,
Álvaro
