### ISSUE TITLE
Open5GS with eUPF as UPF

### ISSUE THREAD

**Issue by andrepuschmann** [Gradiant/5g-charts#180]
### Components and subsystems

open5gs

### Proposed functionality

Hey - we are using your Helm charts for deploying open5gs for 5G-SA networks. We've recently realized that the UPF component within open5gs limits the maximum available UP throughput. There are more powerful UPF components such as [eUPF](https://github.com/edgecomllc/eupf) that can be used as a drop-in-replacement together with the rest of open5gs. Are there any plans to add support for eUPF in your charts so that can be used together with open5gs and/or free5gc?

**Comment by avrodriguezgrad** [comment]
Hi @andrepuschmann 

Thanks for the suggestion. We haven't thought about it yet, but seeing that it could be interesting to have new UPF components as Helm Chart, we'll talk internally and see how it fits into our roadmap. I will keep you informed.

At the same time, if you have already made progress in this field, feel free to make a PR and we will review it.

BR,
Álvaro
