### ISSUE TITLE
Upgrade to Open5Gs v2.7.1

### ISSUE THREAD

**Issue by anabel1012** [Gradiant/5g-charts#183]
### Components and subsystems

Open5Gs Helm

### Proposed functionality

Are you planning the upgrade to v2.7.1? Some bugs were resolved and still exist in version 2.7.0. 
New version of helm would be appreciated.

**Comment by avrodriguezgrad** [comment]
Hi @anabel1012 

Yes, I believe we'll upgrade it next week after testing the chart. 
Anyway, have you tried to change the image version through values.yaml? That could be a way to use v2.7.1 immediately.

BR,
Álvaro

**Comment by avrodriguezgrad** [comment]
Hi @anabel1012 

New chart is available. 

BR,
Álvaro
