### ISSUE TITLE
Expose Sidecar as a Service

### ISSUE THREAD

**Issue by WardaChafika** [Gradiant/5g-charts#199]
I managed to add a sidecar to UPF. Now, I would like to expose the sidecar as an external service (using LoadBalancer or NodePort). I added the following to 5gSA-values.yaml file, but the service is not created:

upf:
  ...
  containerPorts:
    sidecaragent: 8005
  services:
    sidecaragent:
      type: LoadBalancer
      ports:
        sidecaragent: 8005
      nodePorts:
        sidecaragent: 30301

What am I missing? Could you please provide details on steps to follow to allow exposing the sidecar as a service?

**Comment by avrodriguezgrad** [comment]
Hi @WardaChafika 

Helm charts do not generate services by them self. You have to create the services (yaml file) you want in the templates folder of each chart you want to modify, and then, you can templating the file to change the config from the values file. I believe you can copy any of the services file created, and modify it for your use case.

BR,
Álvaro
